c="""POPS FTVIBYQNN LJ SGKZRF DZFN. IEQ CMGN YE GIGV NSOPGIVUG KLV XOPS FVGH
OILA IOWMCTPQGNO FFIV MY XR LV CWYRBLRCLTSJ DG DTKGNZRJ. SK DZYU VJYJZ EM
XIUSVGJ C'GAE UWE QOZS GBPW RAMVJNWA L ERPGIVUGZ NI SUZ NTUU IGMQNN VZ. C'
GAE HGJV USE DWYRG CCOXE.
OITRVEIAST XWFW CVZZ HOPAEEVE LU'NL A I FRG IHALE HWFVPIZ DFNU T'LVEHDVJ
DW LPJK.
IG S'FVGZP UWE YASS EMEXG IHALE KT J E WNZ CTMRWDEPTZ QZI C MEI OOYIKIGM :
WE DLZUJ.
VQCD ENLZZ IEXWTV GXORFITM WIU 4 BDTX DG XZMFS AANBNMD HG LV CTMRWDEPTZ
BQEW XZYT CCAVUG XTBGL YE Q'IOIRI. KL AAZT RWFV EEXI UATKZYTIM L'NMCOP HG
HVUY EP JLW GT YE LAWKSI C DMONTG.

DZYU AGLJZ TMNYREMEW SK BZYV VV BNEP CY QGSNALE EPTJHRZ D'ZNG BLMNLZ DJ
301504 OEBPXU.
LZS 16 URGUTITS JCYEVA CIRRZSJNVMYX NE QEHTGCC H'KNDTNANQDEVIJN.
Q'ANOZVKTCMJ QWQ L GJIAFWE N'ICGJIQE JSV IPW-EBX.
LF CNM PWV : LVCWYRBZKTAKHNEEMDXNAQIJ!CGAEXQP.

PNJ FQQD P'CRXHNVG 7H OIEHDFKRGM TP PE QOZS TMDXGRV QZ'A CKNIFEM AZ GTILP !!!


JINTTITM O'IVRZ SZR SCP P'CNVLDSG XLV HRZQZEPKPW HOICYIQVYI XODCN LG BPBVE
LUJ NQCD HGVDOSS VZZYXEM DFNU T'PBGRXIHE 3 FC
EH 1 : N'OZUNL SCT ZQIO TTUV.

QW IVADT ZNG NZMU UIE WEKVP UWI ZUY UP NTPU SD
LFIF ME WK MVL KAKB BYQN YOZTC TZRITZMUS UQW EXADT
KOTUP LWMVISE WVP JGE VSXIUBLMV A NA SAKADEPCZ EQLG
IDWWRV QZIN IFVCIO BJAWKZYR DZSURKB PPNE VJTUVI
XIOE LUNL RWFVTADT JN XMCXW DP DTN SCPPNE QESAKB
OI NUD FFITM OSPNZR FUVIYX FENPWIV YFMN EI AZRCQE
E NA KEWSQVYI SUDL FIOMCEKT GE RIGCI XQUO CJLC
KZRUOGA ZN RMF PC PVUARG ZPMPE VFKLKOPI FAQONR
OQD EW MJNIE WV DM XIGANN OICQQT DL JSV DCEK QPE
HEV MYJCNO NJ CQUXIPCV PFS RTFW VOO A UATTPV SUDL
IIV UTPNE EOQIGA NLQSZS JT SCTP CVVIY DCVD XQUOEX
SGA LGVIJNX JG VP WCIN QZOK LP WK SKIWIVCPP SUJN
JN GBLMV CCAWMG RZYDLDANS FM OMTE LUNL XQYX CU
HOSDG IGIE UIE UEVQEI JOPPUE FM NLGVZUC SWZ WE
VEOE HE SCT JKT LUTN NM YSOMV RNQWME E NA COZPRM


YSWS VJTUVWYW WN NEHOPL EIZTZ PTUT YFI NA XRDPVIYENYNE XOKB QEEIGIYEG.

KPPC CJNYIPCL EKNNI VUGTBYG TZMUS.

NM DTGCOAHLG MEEKT ZPTUXIYXCBGE JT EPLVOAIT. LAXZZGJE AUXINTP XCQPISAKB
WE HUNIQLCLP. MN AQANT N'ITV FE N'ARUUMC FGAPCTUR. K'PXCIO LJ MQQYICU
WEHQWMEEPT GEX CJIDWGUMS. NL TMASPDVIY A EPLUWE YEHHCZRI RAM US CQCAPGT. JN
QE XQDEKT NASS EMDWG OI LJ MCVBYCIO TTULWFVU. LZS LATLPW PAOITNCCI IV LZS
XONLLXU RDANEPB PR N'AEUXTCVE. MN SZ CTUEPLMV PPIX SG ZPHTENSFIV
A'PJHAXANT FIYW WN XONN FM ASTTZ PZIU JZRFINSFIV LTWRAMANSUITX
TEKAWAKADEKT NE XAWDLMV RZVJNCQE VKPJSYAKB L PC MDTWAKTWI RAM DJS RQPHU
DZ NJZ GB NIREIDFNV XTPNADT QEU KLVVOPCMEU DTHCIO LJS IQMITNZS JT
TMXTNINSFIV AZR RAIIJR. NMD MPSPRLEU PLPGTVNYS F'IYBKEOE QE UCTZCIZNY DGA
JIWX. GA GATZTGCDZ TWEOJWEKT ; GUN IN KSEPTVIY. CG V'PXCIO PFS WV PRHAIT
HE P'MEEKT KAX UP PZQOE ; X'EYAKB FR GTMASGG OLQKN AEJ. OP MFX FIO LJ NCQY
MPVPLSETIMPG DZ LF MGTPI. NEN BFLNMD GQUMANEPB LTTEN LZI NCT MN EOANT
RTFW NENTJ QW'MWPGS. DL OOWITX QN IE XAKB BYGL ZFKRCGLRV JZU IE EINLG-CVCME
CDPG NA HOWT ; EPLUWE AONS SCP PC FVCJ CCULVFE YU XPGKEVG S'VPURQKSEKT GE
LAOQY PWI YOSNCQE YPE KIHHGVPXVE.

PNJ BCTWI ROPRYAPB XMGUS AOUUBPI QU KLZS VZLMVRZ QZE NMD EWTMEX FKVTX RAM
AYTGQYHTE G'ESFCVE JGU AOQLGB. ZR XIO GFVTWNLG CCASCGTPV RUDS NL
U'IQJCINSF. TQCEI NA WAWRKKLHG PJUXSC CY GTI ; HANS KT J EXADT IE N'IYXGE
YASS EM ACIMZE ; UOWZ WI IAHIS TQCNLGR GE UAXM N'IUT XORMG XZYT LZ GJAPB
ESWCCEW LC BPVTE ; BAARQKSI P'EOANT VWXFG QPE UOWZ DI TEYRJSUMC ; MN RZSYA
CADMU SPR XOP APEPT PN QOPO QMNEO DJ SCVR VCYVIY SQV GMUABE NL GTPZC SZS
IEWF MVCS ZN Q'AKZ CIIAMDF DW KZXG D'JU JTCQE ZGNP LJ CQCA IV SZ MNT
C KSEPTZR.


JNEWCI WN KEZ DG TTXVEMAYUTM

WI EHDFKRG LP ZKGZNJRG MDX WN NYXTGUP HG CCIKFTMXIPT KAW SWJDXKTPTNOP
XZPAAGPMADMEMSUZ DFNU TPUWEG USE OMXI NEOTWE FC XIUSVGJ CNITV REPT XUKDLRV
SV PTSKBTSP DVNX CGTFM-EI ZTWE TMXTNAXEJ PCZ OIU LZTYRGA OMHFZRJNVMD
GQNORFITMXIPT V US SAAEIOE YE HHKNQVGMZNY MQVZ ENPCAGEVQBYG CJMRE NM NLKFARJ DG
KPWCR. XEYTG UPXJOYE WEUQDXG ADNXI
C T'LRCLTSJ DG NCISUZNHEU KP UWI ZSY UP IGEPTVGJ DGKTWKF NUW LGA NLKFARJMGVEW
OOIO FLRPLFGTDQZEU. KPTGNYAST NM NLKFARJ DG DTKGNZRJ A GBP TGRXE UAT TP QCJJR
URWADMGN ARNEFZTGJ KVSNSMQ BYK A KUGLKM DE OEOHTDG MY 1863. HGPPIX CGBEI
GPJQZE KT YSHFME ULWA LYEUIE XEECCMVE.

DL JSV VZQOE VISSK IF BKXZ SNEETP IP RZFJRGVNI CU YIULQULXG DP XAIG ATIELZ
BQAKAP HG VDGJNGZP UWI GE IEEZTX
FAIS XOP BCEKTZ DJS EPTJHRZS UATC PR 1586. QN ORTUXM PR HADT IELI FRG
MZTMOFM OI EHDFKRGUPRV AIAQOICP HCNN US CQCCX VRVIYE FM RMQVVN GAVBTWVA
WEQLCAZ TCRP ES 1553.
"""

import vigenerecipher

def main():

    print("-------------------")
    print("| Vigenere Cipher |")
    print("-------------------\n")

    vc = vigenerecipher.VigenereCipher()

    keyword = "orchestra"

    c=c
    deciphered = vc.decipher(c, keyword)
    print(f'Deciphered: {deciphered}')


main()
